MvcSeriesAWSELB/Models/ErrorViewModel.cs
using System;

namespace MvcSeriesAWSELB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcSeriesAWSELB/Models/Serie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcSeriesAWSELB.Models
{
    [Table("SERIES")]
    public class Serie
    {
        [Key]
        [Column("IDSERIE")]
        public int IdSerie { get; set; }
        [Column("SERIE")]
        public string Nombre { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("PUNTUACION")]
        public double Puntuacion { get; set; }
        [Column("ANYO")]
        public int Anyo { get; set; }
    }
}

MvcSeriesAWSELB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcSeriesAWSELB.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcSeriesAWSELB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcSeriesAWSELB/Controllers/SeriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcSeriesAWSELB.Models;
using MvcSeriesAWSELB.Repositories;

namespace MvcSeriesAWSELB.Controllers
{
    public class SeriesController : Controller
    {
        private RepositorySeries repo;

        public SeriesController(RepositorySeries repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Serie> series = this.repo.GetSeries();
            return View(series);
        }

        public IActionResult Details(int id)
        {
            Serie serie = this.repo.FindSerie(id);
            return View(serie);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Serie serie)
        {
            this.repo.InsertSerie(serie.Nombre, serie.Imagen, serie.Puntuacion
                , serie.Anyo);
            return RedirectToAction("Index");
        }

    }
}

MvcSeriesAWSELB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">ELB Application</h1>
    <img src="~/images/image1.png" />
</div>

MvcSeriesAWSELB/Views/Series/Create.cshtml
@model MvcSeriesAWSELB.Models.Serie

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Serie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Puntuacion" class="control-label"></label>
                <input asp-for="Puntuacion" class="form-control" />
                <span asp-validation-for="Puntuacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anyo" class="control-label"></label>
                <input asp-for="Anyo" class="form-control" />
                <span asp-validation-for="Anyo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcSeriesAWSELB/Views/Series/Details.cshtml
@model MvcSeriesAWSELB.Models.Serie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Puntuacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Puntuacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anyo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anyo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdSerie">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcSeriesAWSELB/Views/Series/Index.cshtml
@model IEnumerable<MvcSeriesAWSELB.Models.Serie>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntuacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anyo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Puntuacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anyo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdSerie">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdSerie">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdSerie">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcSeriesAWSELB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcSeriesAWSELB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/deadpool.png" style="width: 40px" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                               asp-controller="Series" asp-action="Index">
                                Series AWS
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">Series</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Producto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcSeriesAWSELB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>